In [38]:
import numpy as np
a=np.ones((12,1))
b=np.random.randint(18,30,(12,1))
c=np.random.randint(60,82,(12,1))
X=np.concatenate((a,b,c),axis=1)
print(X)
print()
Y = np.random.uniform(13.5, 18.6, (12, 1))
print(Y)
print()
A=np.linalg.matrix_power((X.transpose().dot(X)),-1).dot(X.transpose().dot(Y))
Y1=A[0]+A[1]*X[1]+A[2]*X[2]
print(A)
print()
print(Y1)

[[ 1. 29. 78.]
 [ 1. 29. 60.]
 [ 1. 18. 60.]
 [ 1. 19. 61.]
 [ 1. 21. 72.]
 [ 1. 26. 67.]
 [ 1. 18. 72.]
 [ 1. 18. 70.]
 [ 1. 21. 72.]
 [ 1. 19. 66.]
 [ 1. 28. 73.]
 [ 1. 18. 62.]]

[[13.67325708]
 [15.15926739]
 [14.89735707]
 [14.2442089 ]
 [14.921161  ]
 [13.97846599]
 [14.53593961]
 [14.90467361]
 [14.20894597]
 [13.90339457]
 [13.95955834]
 [13.95929756]]

[[ 1.64349443e+01]
 [-1.21249618e-02]
 [-2.66578291e-02]]

[16.39616155 15.60347952 14.10797689]
